### PR TITLE
read package path from go.mod if it exists

### LINKED ISSUE #29: build fails in go module
Steps to reproduce:
```bash
mkdir testgrift && cd "$_"  #(outside of $GOPATH)
git init
git remote add origin git@github.com:rrrkren/testgrift.git
go mod init
grift init
grift hello
```
gives error:
```
build github.com/rrrkren/testgrift/.grifter: cannot find module for path testgrift/grifts
exit status 1
```

when I do this process without the git part everything work fine

### PR DESCRIPTION
**Pull request by rrrkren**
this fixes #29

### CODE REVIEW

**Comment by markbates** [comment]
Thanks! Can we switch it using this https://godoc.org/github.com/rogpeppe/go-internal/modfile#ModulePath instead? should be more resilient. :)

**Comment by rrrkren** [comment]
haha that's some nice round wheels I reinvented, was actually looking for some built in stuff like this. I'll make the changes :)

**Comment by rrrkren** [comment]
@markbates what do you think should happen if the go.mod is malformed and the package path cannot be found? Should we return an error or infer it from the current path?

**Comment by markbates** [comment]
if mods are on:

* go.mod found - read module name
* go.mod not found - error
* go.mod malformed -error

If mods are off:

* infer from path

how's that sound to you?

**Comment by rrrkren** [comment]
sounds good :) so we check for GO111MODULE env first?

**Comment by markbates** [comment]
Yep, if it’s on then use mods. That’s the pattern we’re taking everywhere else. We don’t have “auto”. :)

--
Mark Bates
CTO/Founder

**Comment by rrrkren** [comment]
should be working now, using v1.0.0-alpha for go-internal/modfile, only change from 0.0.8 to alpha seems to be changing of name from mod-internal to go-internal.

**Review by markbates — APPROVED** [review]

**Comment by markbates** [comment]
Thanks! I noticed another issue when trying this that needs to be fixed before I can cut a release.

**Comment by markbates** [comment]
@rrrkren v1.0.5 should do it! :)

**Pull request merged**
